### ISSUE TITLE
Provide an errorElement to show when the router fails (e.g., chat.save())

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#181]
![image](https://github.com/tarasglek/chatcraft.org/assets/857083/43297270-1e92-485c-9445-23dbed139302)

Looks like save() can throw, there are a low of unprotected saves https://github.com/tarasglek/chatcraft.org/blob/4ba2d0ec9393df8e9240fcb5e4211ef5073dd01a/src/router.tsx#L31

They are intermittent cos they happen during routing. This renders app unusable for some users.

**Comment by humphd** [comment]
cc @Chigala, can you add context to this please?

**Comment by Chigala** [comment]
Opened the production site and this error popped up, The error persisted even after refreshing the page and clearing the data in my localstorage,I couldn't use chatcraft.org for that whole day. The next day there was no error. The dev site had no errors all throughout, it was only the production site.

**Comment by humphd** [comment]
The dbs for local dev or production are independent (i.e., you're using IndexedDB locally in the browser for that origin).

This error implies that [Dexie (our db library) couldn't open the db](https://dexie.org/docs/DexieErrors/Dexie.DatabaseClosedError), or did and it got shutdown for some reason.  The total lack of anything useful in the error message makes me think something odd happened with the db in the browser (resource constraints?). Especially since it fixed later on.  Is your computer low on resources, or were you using a lot of other things at the time?

At any rate, this sucks and we should probably add an [`errorElement`](https://reactrouter.com/en/main/route/error-element) so we can render something more useful when things break at the db level (there's not much we can do to recover from that).

Based on the call stack, you likely landed where @tarasglek suggests above, namely: https://github.com/tarasglek/chatcraft.org/blob/8b137cf16350f5092b3b60e0426d311f43804f88/src/router.tsx#L31.  This would be called if you went to `/` which redirects to `/new` which creates an item and then redirects to `/c/:id` so you can view it, saving the item before navigating to it.

If you ever hit this again, go look at IndexedDB vs. localStorage to see what's happening.

**Comment by Chigala** [comment]
My computer was low on resources at some point and I was running a lot of stuff at the same time. Now you've explained how it works, I think that was the culprit. Yeah, if it ever happens again I'll check the indexedDB. Thanks

**Comment by humphd** [comment]
The app can't run without the db, since it's our reactive datasource.

The database being unavailable is a major problem not an app problem (i.e., we can't route around it).

What we can do is show custom error UI.  How about this: 

<img width="1114" alt="Screenshot 2023-07-27 at 9 37 16 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/109f47aa-6185-49b3-92aa-a1b1642256c3">

**Comment by humphd** [comment]
Closing other tabs and refreshing will fix it.  This is an edge case.

**Comment by tarasglek** [comment]
ok, your ui makes sense then
