### ISSUE TITLE
Ability to change and resubmit previous prompts

### ISSUE THREAD

**Issue by DukeManh** [tarasglek/chatcraft.org#277]
When I change the last prompt and save, the prompt is not resubmitted. I kind of expect the button to resubmit the prompt and continue the conversation from there, like chatgpt.

Is this the intended behaviour or can we have a 'Save & Submit' button?

**Comment by humphd** [comment]
I think "Save & Submit" is reasonable.  We have some code to check whether to allow or ignore the user pressing the prompt button, see:

https://github.com/tarasglek/chatcraft.org/blob/main/src/Chat/ChatBase.tsx#L194-L206

To make this work, we'd need to somehow also be able to say, "This chat has changed since it was last sent, and it's OK to send it again".

Probably having `Save` and `Save & Submit` on all editable messages makes sense, since the whole chat has been altered.  I wouldn't want it to be the default, since I often need to edit a few things, then write a new prompt, before it's ready to send.

It's also possible that we shouldn't try so hard to block the prompt button from sending text.  We've had a few bugs related to this.

@DukeManh you want to try a fix?

**Comment by DukeManh** [comment]
That makes sense. Thanks @humphd.

I can try adding it.
