### ISSUE TITLE
Sometimes messages lose code

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#32]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/857083/235657160-0ea24dc6-ce33-46f3-9bf5-b27e8cd5fc18.png">

No idea what causes this, guessing it's something to do with serialization/deserialization as it started happening after one of the recent refactors.

**Comment by humphd** [comment]
I can't reproduce locally or on chatcraft.org.  I tried with both gpt-3.5 and gpt-4:

<img width="1109" alt="Screenshot 2023-05-02 at 8 02 56 AM" src="https://user-images.githubusercontent.com/427398/235661093-b12af1d5-541e-46b7-8cae-6c5afdefc2ef.png">

<img width="1111" alt="Screenshot 2023-05-02 at 8 04 09 AM" src="https://user-images.githubusercontent.com/427398/235661146-e2a95846-612a-40d8-a78b-628ffd490f89.png">

I wonder if we're hitting https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/513 upstream.

**Comment by humphd** [comment]
Refreshing a few times I can get it:

<img width="1113" alt="Screenshot 2023-05-02 at 8 14 36 AM" src="https://user-images.githubusercontent.com/427398/235663352-75fa25ed-ede6-4f92-9844-2bd1bc3bd043.png">

Refreshing again and it's working.

**Comment by tarasglek** [comment]
yeah it's been hard to repro here too.

**Comment by humphd** [comment]
Seems to only happen for me in a production build, which is why I've never hit it (I tend to play with this locally in development).  I've confirmed that it's not coming from our code.  When we hit it, we aren't passing down `'[object Object]'` but the actual code we want to work with:

<img width="1122" alt="Screenshot 2023-05-02 at 8 33 21 AM" src="https://user-images.githubusercontent.com/427398/235667192-be31f68e-de53-49a4-b80a-032d3cc3f648.png">

It's happening once we hand it off to the component here: https://github.com/tarasglek/chatcraft.org/blob/main/src/components/Markdown.tsx#L161

I'm trying to trace it through, to see if I can spot something.

**Comment by tarasglek** [comment]
https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/513

**Comment by tarasglek** [comment]
Linking your post to https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/513

**Comment by tarasglek** [comment]
prismjs does seem to have an autoloader plugin. https://prismjs.com/plugins/autoloader/
I used it before, didn't run into show-stopper glitches, just couldn't find autoloader before.
