### ISSUE TITLE
Do not require chatcraft users to enter a key to use it

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#401]
If a user does not enter a key, we should use a free model endpoint provided by something like https://taras-free_open_router.web.val.run implemented by https://www.val.town/v/taras/free_open_router .  Should still have a banner prompting for user to enter their key while in limited to free models mode.
This makes use of a new openrouter feature where free models are singled out with :free suffix

**Comment by tarasglek** [comment]
Sample curl
```bash
curl 'https://taras-free_open_router.web.val.run/api/v1/chat/completions' \
     -H 'accept: application/json' \
     -H 'authorization: Bearer THIS_IS_OVERRIDEN_ON_SERVER' \
     -H 'content-type: application/json' \
     --data-raw '{
  "model": "openchat/openchat-7b:free",
  "temperature": 0,
  "messages": [
    {
      "role": "system",
      "content": "I am ChatCraft, a web-based, expert programming AI assistant. I help programmers learn, experiment, and be more creative with code.\n\nI follow these rules when responding:\n\n- Use GitHub flavored Markdown\n- ALWAYS include the programming language name (js) or type of data (csv) at the start of Markdown code blocks\n- Format ALL lines of code to 80 characters or fewer\n- Use Mermaid diagrams when discussing visual topics\n- If using functions, only use the specific functions I have been provided with\n- If responding with math, use KaTeX syntax in your Markdown by enclosing it with double-dollar signs rather than parentheses, for example: $$O(n\\log n)$$\n"
    },
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "stream": true
}' 
```

**Comment by humphd** [comment]
@kliu57 this fits nicely with what you're doing with the `ChatCraftProvider` class.  Do you want to tackle this?

We should consider taking a bunch of the code in `ai.ts` and moving it to specific classes that extend `ChatCraftProvider`.  For example:

- create `providers/OpenAiProvider.ts`, `providers/OpenRouterAiProvider.ts`, `providers/TarasFreeOpenRouterProvider.ts` (or maybe just `providers/FreeProvider.ts`, `providers/DefaultProvider.ts` ?).
- Implement specific versions of `createClient`, `defaultModelForProvider`, `querModels`, `validateApiKey`, etc. that live on each of these providers, and do things specific to that provider.

Then the logic for working with an AI provider can be abstracted so that we mostly call these methods without worrying about the details.

**Comment by kliu57** [comment]
@humphd Sure, I can take this.

**Comment by kliu57** [comment]
> @kliu57 this fits nicely with what you're doing with the `ChatCraftProvider` class. Do you want to tackle this?
> 
> We should consider taking a bunch of the code in `ai.ts` and moving it to specific classes that extend `ChatCraftProvider`. For example:
> 
>     * create `providers/OpenAiProvider.ts`, `providers/OpenRouterAiProvider.ts`, `providers/TarasFreeOpenRouterProvider.ts` (or maybe just `providers/FreeProvider.ts`, `providers/DefaultProvider.ts` ?).
> 
>     * Implement specific versions of `createClient`, `defaultModelForProvider`, `querModels`, `validateApiKey`, etc. that live on each of these providers, and do things specific to that provider.
> 
> 
> Then the logic for working with an AI provider can be abstracted so that we mostly call these methods without worrying about the details.

Broke this issue into a smaller issue #478

**Comment by kliu57** [comment]
@humphd Should I move queryModels and createClient from ai.ts to providers/index.ts? Also, what should be my next steps for this PR?
