### ISSUE TITLE
Can only see 1 model in free models

### ISSUE THREAD

**Issue by Rachit1313** [tarasglek/chatcraft.org#534]
1. I only see one model in free models and the error below in console
![image](https://github.com/tarasglek/chatcraft.org/assets/58596563/ad2c4a67-2d46-4154-aa0b-55cba6d9e16e)

2. Random errors including, sometimes when I switch from free to openRouter, no new models added 
https://github.com/tarasglek/chatcraft.org/assets/58596563/bfc43bcb-6f46-4547-925f-34093be91814

or sometimes when I switch from openrouter to free, even the free selected show all other models

https://github.com/tarasglek/chatcraft.org/assets/58596563/c9feb786-983d-44d7-9392-1d3e515c00e0

**Comment by humphd** [comment]
From discussions on Discord, this seems to have been a network issue vs. ChatCraft issue.  If we don't have network, we can't load models or talk to the providers.

**Comment by Rachit1313** [comment]
It is something related to network configurations which disrupts functionality of switching providers. My network was able to get models from openrouter and openAI but was not able to access free models API which caused this.

**Comment by humphd** [comment]
It might be good for us to figure out how to show an error when we can't load what we need from a provider.

**Comment by kliu57** [comment]
@Rachit1313 Since this issue is resolved for you maybe you could close this issue and create a new one related to showing an alert banner or an error message when we are getting these kind of problems. We could fine tune the details during the next team meeting. Would be difficult to test but would be useful to have when users are experiencing network or internet issues.

**Comment by Rachit1313** [comment]
sure.
