### ISSUE TITLE
Better icon for unknown models

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#611]
We currently use the OpenAI logo when we don't have a specific logo.

For example, I followed @tarasglek walkthrough today to set up an account on [Grok](https://groq.com), made an API key, and add them as another free provider using the API URL https://api.groq.com/openai/v1.

<img width="953" alt="Screenshot 2024-04-23 at 10 19 28 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/05e03654-991a-4fa1-b11a-06ab39c9fb75">

Here I'm using Meta's new llama3-70b (wow it's fast!), but the icon makes it look like an OpenAI model.

We should probably do two things:

- Add icons for models that start with names we know (e.g., llama* could use some llama icon)
- otherwise, we should probably fallback to something like https://react-icons.github.io/react-icons/search/#q=robot

**Comment by mingming-ma** [comment]
https://github.com/lobehub/lobe-icons?tab=readme-ov-file

seem pretty good for the Popular AI / LLM Model Brand SVG Logo and Icon Collection.

**Comment by mingming-ma** [comment]
@humphd I tried with some llama icon but due to the avatar size, I think it is not good as expected  as it becomes small and hard to recognize. 
<img width="184" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/b1902fa7-08b6-4776-8c56-0c62b86a324d">
<img width="188" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/c751afcb-2465-4ee5-be49-61ff0da7e11d">

<img width="1101" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/7a03ed61-eb3c-4e40-9d5f-5961f5ccee8c">


How about use Meta icon for `llama` models?

<img width="189" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/02ca61e5-d894-4f78-bd84-3ad653611d13">

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/fb1cb734-68de-42e8-b5ef-bf2da89e166b)

**Comment by humphd** [comment]
This has been fixed.
