### ISSUE TITLE
Add safe-bottom padding on mobile iOS

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#655]
The new changes just landed in #654 are amazing.  I was trying them today on my iPhone, and I notice that we could use a little more safe-padding on the bottom, see https://webkit.org/blog/7929/designing-websites-for-iphone-x/:

![Screenshot 2024-06-17 at 5 30 32 PM](https://github.com/tarasglek/chatcraft.org/assets/427398/95504bfb-b663-4da0-a941-5a6c181ee739)

**Comment by gitdevjin** [comment]
Hello @humphd.
I am interested in this issue and was trying to fix it.
On the inspect page of Chrome, it seems to need extra padding on the bottom.

On inpsect:
<img width="1201" alt="Screenshot 2024-10-25 at 4 46 22 PM" src="https://github.com/user-attachments/assets/90cb8c4f-bf11-4c79-9eb4-3db11372bda6">

However, on my phone(iPhone pro 15) using different browsers, Safari, Chrome, [Naver](https://apps.apple.com/us/app/%EB%84%A4%EC%9D%B4%EB%B2%84-naver/id393499958)
I looked fine due to the navbar on the bottm.

### Chrome:
![IMG_0722](https://github.com/user-attachments/assets/3ddfb4cd-39bb-4705-afc3-a9a8b8282eae)

### Safari
![IMG_0723](https://github.com/user-attachments/assets/22a858fa-15b2-4212-89f7-22da134eacc0)

### Naver:
![IMG_0724](https://github.com/user-attachments/assets/7ad4c810-8698-4738-802d-0416d5891941)

Could you let me know what mobile browser you used or how you entered the chatcraft page?

**Comment by tarasglek** [comment]
You need to add it to home screen via share function first ![IMG_EBAF7359206F-1](https://github.com/user-attachments/assets/439351ad-72cf-4ae6-b242-c75e7b30573d)

**Comment by humphd** [comment]
Fixed in #705
