### ISSUE TITLE
When sharing, login should return to the chat you were working on

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#91]
This one caught me by surprise. I had one old chat and a newer chat...eg if i open a new chatcraft it opens newer chat.

I then go to share older chat, it asks me to login and then returns to newer chat...i seemingly lose the older chat..luckily i could get back via search.

**Comment by humphd** [comment]
Help me reproduce.

So if I go to `chatcraft.org/` right now, it takes me to the latest chat, which is https://chatcraft.org/c/zJAbsFS1ZTzY6tQI5Daki for me.

Then you are making a new chat by clicking ***New > Blank Chat...***?

Now I have https://chatcraft.org/c/d9mMqEvKTh-6eQwbAxGQY (new) and https://chatcraft.org/c/zJAbsFS1ZTzY6tQI5Daki (old).

When I open chatcraft/ again, it takes me to https://chatcraft.org/c/d9mMqEvKTh-6eQwbAxGQY (new).

That seems right to me, since https://chatcraft.org/c/d9mMqEvKTh-6eQwbAxGQY (new) is the most recent.

Maybe what we need here is to add a **Recent** list to the sidebar, which shows your last 5-10 chats above the Shared chats?

**Comment by tarasglek** [comment]
made a recording..will share it once it finishes uploading

**Comment by humphd** [comment]
See #93 too.

**Comment by tarasglek** [comment]
see vid
https://github.com/tarasglek/chatcraft.org/assets/857083/09924153-6815-41cc-81fb-ddbd7f67ad5e

**Comment by humphd** [comment]
Got, so this is about the fact that doing a login redirects back to `/` vs `/:currentId`.  That's a bug for sure, nice find.
